### ISSUE TITLE
Potential bug with reading existing Schunk from file?

### ISSUE THREAD

**Issue by kkotyk** [Blosc/python-blosc2#204]
Does this line have a bug, or am I incorrectly understanding how to load an Schunk from file?
https://github.com/Blosc/python-blosc2/blob/7fac85e8035f7c7de66580f2ead60990a0ae2420/blosc2/blosc2_ext.pyx#L944

Should this line actually be?
`self.mode == "r" and urlpath is None`

**Comment by FrancescAlted** [comment]
That's a good question.  May be @JanSellner can shed some light on this.

**Comment by JanSellner** [comment]
Actually, the (rare) use case of opening a SChunk with `mode="r"` is currently not possible because `blosc2_schunk_new` is called in `SChunk.__init__` and this requires a non-existent file, i.e. opposite of what ``mode="r"`` requires. The tests also skip this case at the moment.

I created a PR #206 to fix this (rare) use case.
