### ISSUE TITLE
Wheels names for win are broken

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/python-blosc2#247]
After adopting dynamic versioning in new build machinery, wheels for windows to be released are broken.  One can see that PyPI does not like uploading wheels with such names here: https://github.com/Blosc/python-blosc2/actions/runs/10595547569/job/29363601536#step:4:39

Any hint, @LecrisUT ?

**Comment by LecrisUT** [comment]
That is odd, because the version specifier seems fine: https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers

What is odd is that only one of the builds gained `.dev0+gcb1dcfc.d20240828` suffix, which it should never have if it's on a tag. Let me forward this issue upstream

**Comment by LecrisUT** [comment]
Ah, I have a clue. The suffix there indicates that the commit was cb1dcfc, but it also appended the date `d20240828` which only happens if the git environment is dirty [^1]. See also #246 it has the `dYYYYMMDD` suffix appended, so it is possible to fix it inside a PR if you look for that. Most probable cause is some patterns are not included in the `.gitignore`. Maybe one way to debug this is to add a [`tool.cibuildwheel.before-test`](https://cibuildwheel.pypa.io/en/stable/options/#before-test) and `git -C {package} status` (not sure if you need trickeries to make it work for windows or if `cd` would also work)

[^1]: https://setuptools-scm.readthedocs.io/en/latest/usage/#default-versioning-scheme

**Comment by FrancescAlted** [comment]
Sorry, but I don't know what "git environment is dirty" means.  Also, I must be blind, but I'm not seeing where the `dYYYYMMDD` suffix is appended in #246.

Anyway, I have activated the `tool.cibuildwheel.before-test` debug thing, but if I cannot see the problem, I'll file an issue in [setuptools_scm](https://github.com/pypa/setuptools_scm).

**Comment by FrancescAlted** [comment]
FWIW, it looks like the issue only happens for Windows *and* Python 3.11 and 3.12; 3.10 seems fine: https://github.com/Blosc/python-blosc2/actions/runs/10595547569/job/29361557445#step:7:3504

**Comment by LecrisUT** [comment]
Dirty git environment means you have uncommitted files. The suffix `.dev0+gcb1dcfc.d20240828` (in the wheel's name) is decomposed as `dev<N>.g<hash>.d<date>`, where `<N>` is number of commits since last tag, `<hash>` is the current commit hash, and `<date>` is the current date in `YYYYMMDD` format.

**Comment by FrancescAlted** [comment]
Ok, the new run has finished, and the output of `git -C D:\a\python-blosc2\python-blosc2 status` on Windows is providing some hint (maybe?).  For Win/Python 3.10:

```
  + git -C D:\a\python-blosc2\python-blosc2 status
  HEAD detached at v3.0.0-beta.2
  Changes not staged for commit:
    (use "git add <file>..." to update what will be committed)
    (use "git restore <file>..." to discard changes in working directory)
    (commit or discard the untracked or modified content in submodules)
  	modified:   c-blosc2 (modified content)
  
  Untracked files:
    (use "git add <file>..." to include in what will be committed)
  	blosc2
  	src/blosc2/_version.py
```

which IMO seems reasonable.  However for Win/Python 3.11 and 3.12:

```
  + git -C D:\a\python-blosc2\python-blosc2 status
  HEAD detached at v3.0.0-beta.2
  Changes not staged for commit:
    (use "git add <file>..." to update what will be committed)
    (use "git restore <file>..." to discard changes in working directory)
    (commit or discard the untracked or modified content in submodules)
  	modified:   c-blosc2 (modified content)
  
  Untracked files:
    (use "git add <file>..." to include in what will be committed)
  	blosc2
  	src/blosc2/_version.py
  	wheelhouse/
```

So, in this case, a new `wheelhouse/` folder (apparently empty) has appeared, while for Python 3.10 it was not there.  Not sure how this can get into the way of producing a broken version tag, but as it seems to just affect Windows, I tend to think on a relatively subtle bug in `setuptools_scm`?

**Comment by LecrisUT** [comment]
Those are red-herrings, the real issue is that `c-blosc2` has some files changed. Untracked files usually do not create dirty git status. The cahng in `c-blosc2` is really suspicious in terms of CMake. You could try to do further `git diff` to find what went bad there.

I think it's also an issue of the vcs version is calculated before cmake is run so it only got dirty on the next build.

A quick fix would be to switch from submodule to `FetchContent` (I'll write a snippet for that tomorrow when I'm on the laptop), but still the core issue should be fixed. I'll look at the build system there to at least track down the culprit

**Comment by LecrisUT** [comment]
Here is one super suspicions snippet:
https://github.com/Blosc/c-blosc2/blob/b179abf1132dfa5a263b2ebceb6ef7a3c2890c64/CMakeLists.txt#L204-L206

`CMAKE_CURRENT_SOURCE_DIR` must never be written towards. What was that snippet trying to achieve?

Similar issues:
https://github.com/Blosc/c-blosc2/blob/b179abf1132dfa5a263b2ebceb6ef7a3c2890c64/CMakeLists.txt#L242-L243

Why it didn't fail on linux builders, I'm not sure.

---

The `c-blosc2` needs quite a lot of work to review and would probably be a monolith PR. For now I would recommend going the `FetchContent` approach.

**Comment by RonnyPfannschmidt** [comment]
for sanity/safety i recommend adding the version file and wheelhouse to gitignore

the c-blosc2 changes is the culprit for the "dirty" state

**Comment by LecrisUT** [comment]
Here is the lines to change to support `FetchContent`:
https://github.com/Blosc/python-blosc2/blob/cb1dcfccd73d5367a0099e001e4f6213a8990448/CMakeLists.txt#L37
```patch
-    add_subdirectory(${PROJECT_SOURCE_DIR}/c-blosc2)
+    include(FetchContent)
+    FetchContent_Declare(blosc
+            GIT_REPOSITORY https://github.com/google/googletest
+            GIT_TAG b179abf1132dfa5a263b2ebceb6ef7a3c2890c64
+    )
+    FetchContent_MakeAvailable(blosc)
```

**Comment by FrancescAlted** [comment]
After a few hiccups, [python-blosc2 3.0.0-beta.3](https://github.com/Blosc/python-blosc2/releases/tag/v3.0.0-beta.3) is out! (PyPI was picky enough to not allow to reuse the `3.0.0-beta.2` label anymore).  Thanks for all the help on this!
